openapi: 3.0.0
info:
  title: Google Cloud API Example
  description: Google Cloud API specification example
  license:
    name: MIT
    url: ../license
  version: "1"
servers:
  - url: "{protocol}://example.com"
    variables:
      protocol:
        enum:
          - https
        default: https
paths:
  /customers:
    get:
      operationId: getCustomers
      summary: get customers
      responses:
        200:
          description: "hello"
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: google.rpc.status.yml#/components/schemas/google.rpc.Status
                  code:
                    $ref: google.rpc.code.yml#/components/schemas/google.rpc.Code
