openapi: 3.0.0
info:
  title: google-cloud-api extended specification
  description: |
    This is the OpenAPI specification for the [google-cloud-api](https://www.npmjs.com/package/google-cloud-api).
    It is an extension to the [Google Cloud API design](https://cloud.google.com/apis/design/)

    The main focus here is on the error modeling.

    Other specification may be added in the future.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1.0
servers:
  - url: "https://your-awesome-api.com"
paths:
  /google-cloud-api/error/aborted:
    $ref: paths/google-cloud-api/error.aborted.yaml
  /google-cloud-api/error/already-exists:
    $ref: paths/google-cloud-api/error.already_exists.yaml
  /google-cloud-api/error/cancelled:
    $ref: paths/google-cloud-api/error.cancelled.yaml
  /google-cloud-api/error/cause-info:
    $ref: paths/google-cloud-api/error.cause_info.yaml
  /google-cloud-api/error/data-loss:
    $ref: paths/google-cloud-api/error.data_loss.yaml
  /google-cloud-api/error/deadline-exceeded:
    $ref: paths/google-cloud-api/error.deadline_exceeded.yaml
  /google-cloud-api/error/failed-precondition:
    $ref: paths/google-cloud-api/error.failed_precondition.yaml
  /google-cloud-api/error/internal:
    $ref: paths/google-cloud-api/error.internal.yaml
  /google-cloud-api/error/invalid-argument:
    $ref: paths/google-cloud-api/error.invalid_argument.yaml
  /google-cloud-api/error/not-found:
    $ref: paths/google-cloud-api/error.not_found.yaml
  /google-cloud-api/error/out-of-range:
    $ref: paths/google-cloud-api/error.out_of_range.yaml
  /google-cloud-api/error/permission-denied:
    $ref: paths/google-cloud-api/error.permission_denied.yaml
  /google-cloud-api/error/resource-exhausted:
    $ref: paths/google-cloud-api/error.resource_exhausted.yaml
  /google-cloud-api/error/unauthenticated:
    $ref: paths/google-cloud-api/error.unauthenticated.yaml
  /google-cloud-api/error/unavailable:
    $ref: paths/google-cloud-api/error.unavailable.yaml
  /google-cloud-api/error/unimplemented:
    $ref: paths/google-cloud-api/error.unimplemented.yaml
  /google-cloud-api/error/unknown:
    $ref: paths/google-cloud-api/error.unknown.yaml
  /google-cloud-api/error/any-of:
    $ref: paths/google-cloud-api/error.any_of.yaml
