openapi: 3.0.0
info:
  title: google-cloud-api extended specification
  description: |
    This is the OpenAPI specification for the [google-cloud-api](https://www.npmjs.com/package/google-cloud-api).
    It is an extension to the [Google Cloud API design](https://cloud.google.com/apis/design/)

    The main focus here is on the error modeling.

    Other specification may be added in the future.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1.0
servers:
  - url: "https://your-awesome-api.com"
paths:
  /google-cloud-api/aborted:
    $ref: paths/google-cloud-api/aborted.yaml
  /google-cloud-api/already-exists:
    $ref: paths/google-cloud-api/already_exists.yaml
  /google-cloud-api/cancelled:
    $ref: paths/google-cloud-api/cancelled.yaml
  /google-cloud-api/cause-info:
    $ref: paths/google-cloud-api/cause_info.yaml
  /google-cloud-api/data-loss:
    $ref: paths/google-cloud-api/data_loss.yaml
  /google-cloud-api/deadline-exceeded:
    $ref: paths/google-cloud-api/deadline_exceeded.yaml
  /google-cloud-api/failed-precondition:
    $ref: paths/google-cloud-api/failed_precondition.yaml
  /google-cloud-api/internal:
    $ref: paths/google-cloud-api/internal.yaml
  /google-cloud-api/invalid-argument:
    $ref: paths/google-cloud-api/invalid_argument.yaml
  /google-cloud-api/not-found:
    $ref: paths/google-cloud-api/not_found.yaml
  /google-cloud-api/out-of-range:
    $ref: paths/google-cloud-api/out_of_range.yaml
  /google-cloud-api/permission-denied:
    $ref: paths/google-cloud-api/permission_denied.yaml
  /google-cloud-api/resource-exhausted:
    $ref: paths/google-cloud-api/resource_exhausted.yaml
  /google-cloud-api/unauthenticated:
    $ref: paths/google-cloud-api/unauthenticated.yaml
  /google-cloud-api/unavailable:
    $ref: paths/google-cloud-api/unavailable.yaml
  /google-cloud-api/unimplemented:
    $ref: paths/google-cloud-api/unimplemented.yaml
  /google-cloud-api/unknown:
    $ref: paths/google-cloud-api/unknown.yaml
  /google-cloud-api/any-of:
    $ref: paths/google-cloud-api/any_of.yaml
