openapi: 3.0.0
info:
  title: google-cloud-api exteneded specification
  version: "1"
components:
  schemas:
    google-cloud-api.CauseInfo:
      title: Cause Info
      type: object
      properties:
        "@type":
          type: string
          enum:
            - google-cloud-api/CauseInfo
        causes:
          $ref: "#/components/schemas/google-cloud-api.CauseInfo.Causes"
      required:
        - "@type"
        - "causes"
    google-cloud-api.CauseInfo.Causes:
      type: array
      items:
        $ref: "#/components/schemas/google-cloud-api.CauseInfo.Cause"
    google-cloud-api.CauseInfo.Cause:
      type: object
      properties:
        module:
          type: string
        message:
          type: string
        causes:
          $ref: "#/components/schemas/google-cloud-api.CauseInfo.Causes"
      required:
        - message
paths:
  /dummy:
    get:
      responses:
        200:
          description: dummy
