openapi: 3.0.0
info:
  title: Google RPC specification
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: "1"
servers:
  - url: "https://your-awesome-api.com"
paths:
  /your-endpoint:
    get:
      summary: dummy
      responses:
        "200":
          description: dummy
