name: nodejs
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    uses: unional/.github/.github/workflows/yarn2-library-build.yml@main
  verify:
    uses: unional/.github/.github/workflows/yarn2-library-verify.yml@main
    needs: build
