name: release
on:
  push:
    branches: [main]

jobs:
  code:
    uses: unional/.github/.github/workflows/yarn-verify-linux.yml@main

  release:
    uses: unional/.github/.github/workflows/yarn-release-changeset2.yml@main
    needs: code
    secrets: inherit
